spring:
  datasource:
    url: jdbc:mysql://localhost:3306/silinde_dev
    username: silinde_dev_user
    password: silinde87
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true